
[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "TX02 Nerd Font"
style = "Bold"

[font.bold_italic]
family = "TX02 Nerd Font"
style = "Bold Italic"

[font.italic]
family = "TX02 Nerd Font"
style = "Italic"

[font.normal]
family = "TX02 Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_padding = true
# decorations = 'None'

[general]
import = ["~/.config/alacritty/themes/ef-bio.toml"]
# opacity = 0.9
#
# [window.padding]
# x = 2
# y = 2
