SPACESHIP_PROMPT_ORDER=(
  time
  user
  host
  dir
  # git is performance heavy, cpu governer disable if cpu governer @ performance is not worth
  git
  vi_mode  
)

SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_12HR=true
SPACESHIP_TIME_FORMAT=" %D{%I:%M} %F{white}%w" 
SPACESHIP_TIME_SUFFIX=" " 
SPACESHIP_TIME_COLOR=green

SPACESHIP_USER_SHOW=always
SPACESHIP_USER_PREFIX="["
SPACESHIP_USER_COLOR=cyan
SPACESHIP_USER_SUFFIX="@"

SPACESHIP_HOST_SHOW=always
SPACESHIP_HOST_PREFIX=""
SPACESHIP_HOST_SUFFIX="] "
SPACESHIP_HOST_COLOR=blue

SPACESHIP_DIR_SHOW=true
SPACESHIP_DIR_PREFIX=""
SPACESHIP_DIR_TRUNC=3
SPACESHIP_DIR_TRUNC_PREFIX="…/"

SPACESHIP_VI_MODE_PREFIX="\n "
SPACESHIP_VI_MODE_SUFFIX=" "
SPACESHIP_VI_MODE_INSERT="I >"
SPACESHIP_VI_MODE_NORMAL="%F{red}N >"
SPACESHIP_VI_MODE_COLOR=cyan
