;;; workspace-tests.el --- Browser workspace checks -*- lexical-binding: t; -*-
(require 'ert)
(require 'perspective)
(setq persp-suppress-no-prefix-key-warning t)
(persp-mode 1)
(defvar herdr--workspace-sessions (make-hash-table :test #'equal))
(defvar workspace-roots (make-hash-table :test #'equal))
(ert-deftest browser-workspace-placement ()
  (persp-switch "browser-owner")
  (switch-to-buffer (get-buffer-create "owner-editor"))
  (puthash "browser-owner" "owner-session" herdr--workspace-sessions)
  (persp-switch "focused-editor")
  (switch-to-buffer (get-buffer-create "focused-editor-buffer"))
  (let* ((layout (window-state-get))
         (selected (selected-window))
         (arguments (make-hash-table :test #'equal))
         first second)
    (puthash "url" "about:blank" arguments)
    (puthash "__emacs_mcp_herdr_session" "owner-session" arguments)
    (puthash "__emacs_mcp_workspace_root" "/private/tmp" arguments)
    (setq first (webkit-agent-mcp--open-page arguments)
          second (webkit-agent-mcp--open-page arguments))
    (should (equal (persp-current-name) "focused-editor"))
    (should (eq selected (selected-window)))
    (should (equal layout (window-state-get)))
    (should-not (memq (webkit-agent-page-buffer first) (persp-current-buffers)))
    (persp-switch "browser-owner")
    (should (memq (webkit-agent-page-buffer first) (persp-current-buffers)))
    (should (memq (webkit-agent-page-buffer second) (persp-current-buffers)))
    (should (= (length (seq-filter (lambda (window) (window-parameter window 'webkit-agent-browser)) (window-list))) 1))
    (let ((window (get-buffer-window (webkit-agent-page-buffer second))))
      (should (window-dedicated-p window))
      (with-current-buffer (window-buffer window)
        (should (= (length (webkit-agent--tabs)) 3)))
      (display-buffer (get-buffer-create "file-like-buffer") '((display-buffer-use-some-window)))
      (should (eq (window-buffer window) (webkit-agent-page-buffer second))))
    (let ((window (get-buffer-window (webkit-agent-page-buffer second))))
      (webkit-agent-close second)
      (should (window-live-p window))
      (should (eq (window-buffer window) (webkit-agent-page-buffer first))))
    (webkit-agent-close first)))
(ert-deftest browser-unknown-workspace ()
  (let ((arguments (make-hash-table :test #'equal)))
    (puthash "url" "about:blank" arguments)
    (puthash "__emacs_mcp_workspace_root" "/private/tmp/nonexistent-workspace" arguments)
    (should-error (webkit-agent-mcp--open-page arguments) :type 'user-error)))
