#!/bin/sh
current_variant=$(setxkbmap -query | grep variant)

# if variant is not set, set it
if [[ -z $current_variant ]]; then
  setxkbmap -layout us -variant dvorak
else
  # else set previous default layout
  setxkbmap -layout us
fi
