#!/usr/bin/env python3

from wallstreet import Stock
import argparse


def customticker(name):
    stock = Stock(name)
    print(stock.price)
    # return stock.price


def parseArgs():
    parser = argparse.ArgumentParser()
    parser.add_argument('--customticker', help='', type=str)
    args = parser.parse_args()
    if args.customticker:
        customticker(args.customticker)


if __name__ == '__main__':
    parseArgs()
