#!/usr/bin/env bash

keyboard="$(hyprctl devices -j | jq -r ".keyboards | .[] | select(.main == true) | .name")"
qwerty_index=1
dvorak_index=0 # assuming kb_layout = us,us(dvorak)

are_we_gaming=false

handle() {
    local title
    title="$(hyprctl activewindow -j | jq -r '.class')"

    case "$title" in
        steam_app_* )
            if ! $are_we_gaming; then
                echo "Detected game $title, switching to QWERTY"
                are_we_gaming=true
                setxkbmap -layout us
            fi
            ;;
        *)
            if $are_we_gaming; then
                echo "Exiting game $title, switching to Dvorak"
                are_we_gaming=false
                setxkbmap -layout us -variant dvorak
            fi
            ;;
    esac
}

# socat don't work in tty?
# socat - UNIX-CONNECT:"$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do handle "$line"; done
nc -U "$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do handle "$line"; done

