add_newline = true

format = """
[╭──](bold #4f4f4f)[\\[](bold #4f4f4f)\
$username\
$hostname\
[\\]─](bold #4f4f4f)\
[\\[](bold #4f4f4f)\
$directory\
[\\]](bold #4f4f4f)\
([─\\[](bold #4f4f4f)$git_branch$git_status[\\]](bold #4f4f4f))\
[─\\[](bold #4f4f4f)\
$time \
[%D{%b %d}](bold cyan)\
[\\]](bold #4f4f4f)
[╰[─](bold #4f4f4f)](bold #4f4f4f)[> ](bold yellow)
"""

[time]
disabled = false
format="[$time]($style)"
time_format="%H:%M"
style="bold cyan"

[username]
style_user="blue bold"
style_root="red bold"
format="[$user]($style)"
show_always=true

[hostname]
disabled=false
ssh_only=true
style="bold cyan"
format="[@](bold white)[$hostname]($style)"

[directory]
# I spent way too long on this conditional
format="%B%F{green}(%{%F{($read_only)})$path(%F{($read_only)}%})%F{reset_color}%b"
truncation_symbol="…/"
read_only="red"

[git_branch]
format="[$branch]($style)"
style="bold blue"

[git_status]
format='([\[$all_status$ahead_behind\]]($style))'
style="bold green"
